### ISSUE TITLE
Plugin doesn't show up

### ISSUE THREAD

**Issue by spono** [alexbruy/processing-circuitscape#6]
Hi Alex,
sorry to add a new issue on the "Unable to install plugin" list but, after installing it, nothing appears in the 'Processing options -> Providers' menu.
I saw that in the issues raised previously it was due to the Processing version, but here I'm starting from a fresh installation of 2.18.14 on W10.
any hint on where to look for the cause?
Thank you in advance

**Comment by alexbruy** [comment]
@spono are there any messages in the QGIS Message Log? Any messages or errors on QGIS startup?

**Comment by spono** [comment]
ops, I forgot to check there! (BTW, no messages on the startup)
here the message log:
`2017-11-18T11:09:05	2	Could not load provider: Circuitscape
			Traceback (most recent call last):
			  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\core\Processing.py", line 92, in addProvider
			    provider.initializeSettings()
			  File "C:/Users/NM/.qgis2/python/plugins\processing_circuitscape\CircuitscapeProvider.py", line 62, in initializeSettings
			    CircuitscapeUtils.circuitscapePath()))
			  File "C:/Users/NM/.qgis2/python/plugins\processing_circuitscape\CircuitscapeUtils.py", line 58, in circuitscapePath
			    if isWindows():
			NameError: global name 'isWindows' is not defined`

**Comment by alexbruy** [comment]
Ah, my fault. Should be fixed in 0.2.1
